# Jinja and templates
---
- hosts: all
  tasks:
  - name: deploy a simple template file
    template:
      src: template.j2
      dest: /tmp/output.txt
    tags:
      - create
  - name: remove templated file
    file:
      dest: /tmp/output.txt
      state: absent
    tags:
      - destroy
